# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

###############################################################################
#
# Custom Speech Continuous Improvement Pipeline for GitHub Actions
#
###############################################################################

name: SpeechTrainDataCICD

on:
  push:
    # Execute on pushes to master.
    branches:
      - master
    # The push must include updates to training data.
    paths:
      # The path from the root of the repository to the pronunciation data file.
      - "training/pronunciation.txt"

env:
  # `true` if the repository is private and `false` otherwise.
  IS_PRIVATE_REPOSITORY: false
  # See Language Support for available locales:
  # https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support
  SPEECH_LOCALE: "en-us"
  #############################################################################
  # Testing Data
  #############################################################################
  # The name and extension of the .txt transcript file that will be extracted
  # from `testZipSourcePath`.
  TEST_TRANS_FILE: "trans.txt"
  # The path from the root of the repository to a .zip with .wav files and a
  # .txt transcript used for testing.
  TEST_ZIP_SOURCE_PATH: "testing/audio-and-trans.zip"
  #############################################################################
  # Training Data
  #############################################################################
  # The path from the root of the repository to the pronunciation data file. Set
  # to an empty string if you are training an acoustic model.
  PRONUNCIATION_FILE_PATH: "training/pronunciation.txt"
  # The path from the root of the repository to the related text data file. Set
  # to an empty string if you are training an acoustic model.
  RELATED_TEXT_FILE_PATH: "training/related-text.txt"
  # The name and extension of the .txt transcript file that will be extracted
  # from `trainZipSourcePath`. Set to an empty string if you are training a
  # language model.
  TRAIN_TRANS_FILE: ""
  # The path from the root of the repository to a .zip with .wav files and a
  # .txt transcript used for training. Set to an empty string if you are
  # training a language model.
  TRAIN_ZIP_SOURCE_PATH: ""

jobs:
  #############################################################################
  #
  #   Continuous Delivery - create release after updates to training data.
  #
  #############################################################################

  release:
    name: Release improved endpoint
    runs-on: ubuntu-latest
    # Execute when setup, test_data_update, and train_data_update finish
    # executing and pass.
    needs: [setup, train_data_update]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      #   with:
      #     lfs: true

      # - name: Checkout LFS objects
      #   run: git lfs checkout

      - name: Fetch all history for all tags and branches - for GitVersion
        if: env.IS_PRIVATE_REPOSITORY == 'false'
        run: git fetch --prune --unshallow

      - name: Fetch all history for all tags and branches (private repo) - for GitVersion
        if: env.IS_PRIVATE_REPOSITORY == 'true'
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --unshallow

      # https://github.com/GitTools/GitVersion
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@6dfe406
        with:
          versionSpec: "5.2.x"

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@6dfe406

      - name: Set environment variables
        run: |
          echo "::set-env name=CURRENT_COMMIT_HASH::$(git rev-parse --short HEAD)"
          echo "::set-env name=RELEASE_FILE::release-endpoints.json"
          echo "::set-env name=SEMANTIC_VERSION::$GitVersion_SemVer"
          echo "::set-env name=TRAIN_BUILD_FOLDER_PATH::build-speech-train"
